name: Workflow

on:
    push:
        branches:
            - main
    pull-request:
        branches:
            - main
    workflow-dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name : hello-world
          run :echo "Hello World"
          
